[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = src
build_flags = -D BUFFER_TAILLE=1024
board_build.f_cpu = 160000000L
board_build.partitions = partitions_custom.csv
; Plus de board_build.filesystem = littlefs

board_build.filesystem = littlefs
# Dis à PlatformIO de télécharger la bibliothèque LiquidCrystal standard
lib_deps =
    arduino-libraries/LiquidCrystal @ ^1.0.7